# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# This is a close copy of an example at https://hub.docker.com/_/drupal 
# Differences:
#  - environment variables are defined (to be read by Drupal's settings.php)
#  - the 'sites' volume is not an anonymous volume
#  - the other volumes have been removed (as the CMS will be headless)
#  - add a Postgres DB (only required for local development)
#  - add a nginx webserver (only required for local development)

version: '3'

services:

  drupal:
    build: .
    volumes:
      - drupal_src:/var/www/html
    environment:
      DRUPAL_DBNAME: postgres
      DRUPAL_DBHOST: postgres
      DRUPAL_DBPORT: 5432
      DRUPAL_USERNAME: postgres
      DRUPAL_PASSWORD: example

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example

  web:
    image: nginx:1.15
    ports:
      - "8080:80"
    links:
      - drupal
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - drupal_src:/var/www/html

volumes:
  drupal_src: