name: Article
description: 'Provides Article content type and related configuration. Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.'
type: module
core: 8.x
dependencies:
  - field
  - file
  - image
  - link
  - menu_ui
  - node
  - options
  - path
  - rdf
  - taxonomy
  - text
  - user
