message: "Op zoek naar data en informatie over Amsterdam? Ga naar <a href=\"https://data.amsterdam.nl\">data.amsterdam.nl</a>.\r\n"
langcode: en
_core:
  default_config_hash: Z5MXifrF77GEAgx0GQ6iWT8wStjFuY8BD9OruofWTJ8
