auto_retina.settings:
  type: mapping
  label: Settings
  mapping:
    quality_multiplier:
      type: float
    suffix:
      type: string
    js:
      type: boolean
    log:
      type: boolean
    regex:
      type: string
