id: d7auto_retina_settings
label: Auto Retina settings
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - auto_retina_js
    - auto_retina_quality_multiplier
    - auto_retina_regex
    - auto_retina_suffix
    - auto_retina_log
  source_module: auto_retina
process:
  js: auto_retina_js
  quality_multiplier: auto_retina_quality_multiplier
  regex: auto_retina_regex
  suffix: auto_retina_suffix
  log: auto_retina_log
destination:
  plugin: config
  config_name: auto_retina.settings


